### ISSUE TITLE
Accessory does not appear

### ISSUE THREAD

**Issue by vskal** [alexryd/homebridge-shelly-ng#1]
Thank you alexryd once again for the great work !

Just installed it. I have a Shelly plus1PM in the network but the accessory did not appear after the HB restart.

Even though the plugin is loaded as seen below:

[1/20/2022, 9:44:58 PM] Loaded plugin: homebridge-shelly-ng@1.0.0
[1/20/2022, 9:44:58 PM] Registering platform 'homebridge-shelly-ng.shelly-ng'

the HB log does NOT report the normal platform initialization but a red error message:

[1/20/2022, 9:45:01 PM] No plugin was found for the platform "Shelly NG" in your config.json. Please make sure the corresponding plugin is installed correctly.

Running on docker, latest HB version 1.3.9
Node.js v16.13.1
Npm v8.1.2
Homebridge Network settings, mDNS advertiser is set to Ciao.
Plugin config:
        {
            "name": "Shelly NG",
            "platform": "Shelly NG"
        }

**Comment by alexryd** [comment]
Try this instead:

```
{
  "name": "Shelly NG",
  "platform": "shelly-ng"
}
```

**Comment by vskal** [comment]
Yes it works with this change ! Many thanks !

[Shelly NG] mDNS device discovery started

Switch now appears in Homekit and I must add that switching on/off works very very fast with this new type !

**Comment by andyvirus** [comment]
Same issue, change of platform name as above resolved for myself also. Thankyou!

**Comment by figorr** [comment]
Thank you.
The trick works. 
Just updating the platform to “shelly-ng”  instead of “Shelly NG” and my Shelly 1 plus was discovered.

**Comment by alexryd** [comment]
Awesome. I’ve added it to the README to make it more clear.

Did you use Homebridge Config UI X to install the plugin?

**Comment by figorr** [comment]
Yes I used the Homebridge Config UI X to install the plugin. And the “Shelly NG” value for the platform was by default.

**Comment by alexryd** [comment]
I see. I’ve fixed that bug now and published an update, but you will have to change your config again after installing the update so that it says `"platform": "ShellyNG"`. Sorry about that.

**Comment by vskal** [comment]
Same problem after the update, accessory not found.
This is how the config looks now: 

       {
            "name": "Shelly NG",
            "platform": "shellyNG"
        }

**Comment by alexryd** [comment]
It should be `"ShellyNG"`, with a capital S.

**Comment by vskal** [comment]
Yes it works, sorry I missed the S.
