### ISSUE TITLE
Shelly Pro Dimmer 2PM Homebrige Shelly NG

### ISSUE THREAD

**Issue by DeDe2403** [alexryd/homebridge-shelly-ng#117]
Hello alexryd thank you very much for your great work. I use your two plugins in Homebrige. Shelly and Shelly NG. Now I have bought the Shelly Pro Dimmer 2PM and have already installed it. Is it possible to include it in the Shelly NG plugin or what do you need to include it? Lg Daniel

**Comment by apartmedia** [comment]
This is a duplicate.
See https://github.com/alexryd/homebridge-shelly-ng/issues/111

**Comment by DeDe2403** [comment]
Yes okay
