### ISSUE TITLE
Relais for Door Lock

### ISSUE THREAD

**Issue by Multisaft7** [alexryd/homebridge-shelly-ng#13]
Hey guys,

I using my shelly 1 plus for our new door to unlock. Is it possible to say in the plugin that it is not a switch but rather a lock like here?
![image](https://user-images.githubusercontent.com/33881175/155848886-68a76e54-9242-429f-8b53-44fca65ac810.png)

Thanks

**Comment by alexryd** [comment]
No there's no support for that (at least not yet).

A HomeKit lock requires both a switch to control it and a sensor to tell when it is actually locked. I know some people use the input terminal on the Shelly device for the sensor. Is this what you do too?
