### ISSUE TITLE
Shelly Plus I4 unknown

### ISSUE THREAD

**Issue by barry74** [alexryd/homebridge-shelly-ng#14]
[Shelly NG] [shellyplusi4-083af20109d8] Unknown device of model "SNSN-0024X" discovered.

{"name":null, "id":"shellyplusi4-083af20109d8", "mac":"083AF20109D8", "model":"SNSN-0024X", "gen":2, "fw_id":"20211101-134319/i4prod0-g2345cff-279-i4-production-bundles-2143-dirty", "ver":"i4prod0", "app":"PlusI4", "auth_en":false,"auth_domain":null}

**Comment by alexryd** [comment]
See #6
