### ISSUE TITLE
Support for Shelly Dimmer2 

### ISSUE THREAD

**Issue by d3linma** [alexryd/homebridge-shelly-ng#143]
Please implement the support of the Shelly Dimmer2 to the plugin “homebridge-shelly-ds9” which is a fork of this. Since there is support for Shelly Pro Dimmer 1PM already, I am hoping this is a minor effort.

**Comment by apartmedia** [comment]
The Shelly Dimmer 2 is a Gen1 device. This plugin is for Gen2+ devices.
For the first generation, see this plugin [homebridge-shelly](https://github.com/alexryd/homebridge-shelly).

**Comment by d3linma** [comment]
Ah, thank you!

**Comment by d3linma** [comment]
Ah, thank you!
