### ISSUE TITLE
Unknown device shellyplus2pm

### ISSUE THREAD

**Issue by cjk2** [alexryd/homebridge-shelly-ng#18]
Thanks for the PlugIn. But unfortunately I get for a Shell Plus 2 PM only the message 
[Shelly NG] [shellyplus2pm-a8032ab727c4] Unknown device of model "SNSW-002P16EU" discovered.

Actually, a shutter should be operable via Homebridge here. But this shelly does not appear at all.

What is interesting is that a Shelly Plus 1 appears that I do not have.

**Comment by alexryd** [comment]
Support for the Shelly Plus 2 PM is only available in the beta version at the moment.

Why an unknown Shelly Plus 1 is discovered I don't know.
