### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NorbertM21** [alexryd/homebridge-shelly-ng#2]
Plugin 1.0.1 crashes Homebridge on startup, if Device (shelly Plus 1) is unreachable.

Jan 21 16:40:04 HomeServer homebridge[1301]: [21.1.2022, 16:40:04] [Shelly NG] mDNS device discovery started
Jan 21 16:40:07 HomeServer homebridge[1301]: [21.1.2022, 16:40:07] [Homebridge UI] Homebridge Config UI X v4.42.0 is listening on :: port 8080
Jan 21 16:40:07 HomeServer homebridge[1301]: [21.1.2022, 16:40:07] Error: connect EHOSTUNREACH 192.168.178.40:80
Jan 21 16:40:07 HomeServer homebridge[1301]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Jan 21 16:40:08 HomeServer systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jan 21 16:40:08 HomeServer systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by alexryd** [comment]
Thanks @NorbertM21, this is now fixed in version 1.0.2.

**Comment by vskal** [comment]
With Version 1.0.2 I lost functionality of the 1PM Plus switch.
Reverted to 1.0.1 and functionality was restored.

**Comment by NorbertM21** [comment]
Thanks @alexryd - works fine.
