### ISSUE TITLE
Expose Power Consumption

### ISSUE THREAD

**Issue by TautFlorian** [alexryd/homebridge-shelly-ng#21]
As PM Shellie's offer power measurement it would be nice to expose it to HomeKit as well.

**Comment by alexryd** [comment]
Yes this is on the todo list.

**Comment by borissmart** [comment]
If Power Consumption is integrated, it will be possible to start things when Solar is producing

**Comment by simplytoast1** [comment]
Is there a way to expose a contact sensor (or motion) if power is being drawn vs not?
