### ISSUE TITLE
Shelly Plus 1PM not implementable

### ISSUE THREAD

**Issue by ar1970** [alexryd/homebridge-shelly-ng#23]
After configuring the shelly plus 1 pm manually, i get an error message "[Shelly NG] [shellyplus1pm-441793cf50ec] Unknown device of model "undefined" discovered." 

Shelly Plus 1 PM:
{"name":"Treppenhauslicht","id":"shellyplus1pm-441793cf50ec","mac":"441793CF50EC","gen":2,"fw_id":"20220330-151110/0.10.1-g8d603a2","ver":"0.10.1","app":"Plus1PM","auth_en":false,"auth_domain":null}

Any idea?

**Comment by alexryd** [comment]
Seems like the same issue as #10, that the device doesn’t specify its `"model"` for some reason. I guess it’s a firmware bug. I’ve opened a support ticket, hopefully they’ll fix it soon.

**Comment by ar1970** [comment]
Today I successfully integrated a shelly plus 1. The firmware version of the shelly plus 1 is also 0.10.1 - identical to the shelly plus 1 pm.

**Comment by tojorocha** [comment]
Hello

I have the same problem with one of my shellys plus 1pm
“ Unknown device of model "undefined" discovered”
Should i do something or just wait?

Thanks for your help

**Comment by zscgeek** [comment]
same issue for me
[5/25/2022, 2:24:04 PM] [Shelly NG] [shellyplus1pm-441793cfecd8] Unknown device of model "undefined" discovered.


http://192.168.1.19/shelly
{"name":null,"id":"shellyplus1pm-441793cfecd8","mac":"441793CFECD8","gen":2,"fw_id":"20220330-151110/0.10.1-g8d603a2","ver":"0.10.1","app":"Plus1PM","auth_en":false,"auth_domain":null}

**Comment by alexryd** [comment]
I think this issue has been fixed in firmware version 0.10.2-beta3.

**Comment by tojorocha** [comment]
Yes it was. Thanks a lot
