### ISSUE TITLE
Device Name Shelly Plus 1 not showing

### ISSUE THREAD

**Issue by Kasper05** [alexryd/homebridge-shelly-ng#25]
I have change de Device name in the Shelly Device/app
The name are showing in Logfile but the name is not change in Homekit. He lists it as "Switch 1"
In the accessories tab it also indicates it wrong

For example, if I link HomeKit to LG ThinQ, the name is correct.

**Comment by Kasper05** [comment]
Homekit problem solved. plugin uninstalled and reinstalled as bridge.
Switch 1 is still shown in homebridge accessories, this should show shelly's name.

**Comment by RedFoxie** [comment]
I have the same issue, which blocks node-red to control devices via homebridge.

This it the json dump from homebridge:
`{
  "accessories": [
    {
      "aid": 1,
      "services": [
        {
          "type": "3E",
          "iid": 1,
          "characteristics": [
            {
              "type": "14",
              "iid": 2,
              "perms": [
                "pw"
              ],
              "description": "Identify",
              "format": "bool"
            },
            {
              "type": "20",
              "iid": 3,
              "value": "homebridge.io",
              "perms": [
                "pr"
              ],
              "description": "Manufacturer",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "21",
              "iid": 4,
              "value": "homebridge",
              "perms": [
                "pr"
              ],
              "description": "Model",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "23",
              "iid": 5,
              "value": "Shelly NG 2FDB",
              "perms": [
                "pr"
              ],
              "description": "Name",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "30",
              "iid": 6,
              "value": "0E:3E:86:BB:E4:F6",
              "perms": [
                "pr"
              ],
              "description": "Serial Number",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "52",
              "iid": 7,
              "value": "1.4.1",
              "perms": [
                "pr"
              ],
              "description": "Firmware Revision",
              "format": "string"
            }
          ]
        },
        {
          "type": "A2",
          "iid": 2000000008,
          "characteristics": [
            {
              "type": "37",
              "iid": 9,
              "value": "1.1.0",
              "perms": [
                "pr"
              ],
              "description": "Version",
              "format": "string",
              "maxLen": 64
            }
          ]
        }
      ]
    },
    {
      "aid": 2,
      "services": [
        {
          "type": "3E",
          "iid": 1,
          "characteristics": [
            {
              "type": "14",
              "iid": 2,
              "perms": [
                "pw"
              ],
              "description": "Identify",
              "format": "bool"
            },
            {
              "type": "20",
              "iid": 3,
              "value": "Allterco",
              "perms": [
                "pr"
              ],
              "description": "Manufacturer",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "21",
              "iid": 4,
              "value": "Shelly Plus 1 PM",
              "perms": [
                "pr"
              ],
              "description": "Model",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "23",
              "iid": 5,
              "value": "Tuinverlichting Links",
              "perms": [
                "pr"
              ],
              "description": "Name",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "30",
              "iid": 6,
              "value": "441793CFC488",
              "perms": [
                "pr"
              ],
              "description": "Serial Number",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "52",
              "iid": 7,
              "value": "0.10.2",
              "perms": [
                "pr"
              ],
              "description": "Firmware Revision",
              "format": "string"
            }
          ]
        },
        {
          "type": "49",
          "iid": 8,
          "characteristics": [
            {
              "type": "23",
              "iid": 9,
              "value": "Switch 1",
              "perms": [
                "pr"
              ],
              "description": "Name",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "25",
              "iid": 10,
              "value": 1,
              "perms": [
                "ev",
                "pr",
                "pw"
              ],
              "description": "On",
              "format": "bool"
            }
          ]
        }
      ]
    }
  ]
}`

**Comment by alexryd** [comment]
Accessory names can't be changed after they've been added to HomeKit. This is a limitation in HomeKit and not something that can be changed in this plugin.
