### ISSUE TITLE
Window vs. Window Covering

### ISSUE THREAD

**Issue by MaTr75** [alexryd/homebridge-shelly-ng#28]
I installed a new ShellyPlus 2PM for my Window Covering. I replaced an old Shelly 2.5. The Shelly 2.5 was displayed
 in homekit as "Window Covering" while the ShellyPlus2PM is shown as "Window". Is it possible to configure the ShellyPkus2PM as "Window Covering" as well?

**Comment by Elch08** [comment]
I have the same problem. The roller shutter on my Shelly Plus 2pm is exposed as a Window, and NOT a blind or roller shutter.
Would be much appreciated if you could solve this by an update of the plugin.
Thanks in advance 
Bjoern

**Comment by calamarzo** [comment]
+1

**Comment by Kohlibrie** [comment]
+1

**Comment by boehlefeld** [comment]
+1

**Comment by LukasHiereth** [comment]
+1

**Comment by LukasHiereth** [comment]
+1

**Comment by mschmieder** [comment]
Same issue here. Would love to have the option for blinds instead.

**Comment by aessing** [comment]
Just added a pull request (#41) where I added the choice of device type in the configuration of the plugin.

@alexryd would you mind reviewing the pull request and perhaps allowing it go through.

**Comment by hans-kn** [comment]
I would also appreciate to see this feature in this great plugin.
Is there a way to patch it myself, if it will not be implemented?

**Comment by alexryd** [comment]
Version 1.6.0 that I just released adds a configuration option for changing the cover type from Window to Window Covering or Door.

**Comment by Elch08** [comment]
I cannot find such configuration option. Do I have to add something in the config.json ?

**Comment by ghost** [comment]
I can't find this option either, did I oversee anything?

**Comment by smash14** [comment]
@Elch08 @l579 it is described in the Readme file how to change the settings for device types:

> Only available for devices in cover mode. The type of accessory used to represent the cover. Available options are "door", "window" (default) and "windowCovering".

Just have a look at the table with all the configuration options and search for `devices. cover:0.type`

**Comment by ghost** [comment]
Thanks @smash14 I saw that but it is not working when changing to windowCovering…still displayed as window

**Comment by ghost** [comment]
Could it be, that even I disabled mDNS discovery the devices are found automatically? That way, the default config is used. I even tried disabling mDNS and adding all devices manually, but the plugin discovers all automatically when restarting home bridge and adds them with the default config...

**Comment by DiMaSchine** [comment]
I have the same issue. I have configured the cover as `windowCovering`, but the Shelly 2.5 PM is still being recognized as a windows instead of a shutter. What am I missing? 

`"cover:0": {
                        "exclude": false,
                        "type": "windowCovering" `

**Comment by stealth-modes** [comment]
I have the same issue. With the shelly plus2pm set to cover-mode it was initially recognized als window, after setting
"cover:0": {
                        "exclude": false,
                        "type": "windowCovering"
it is still exposed as window. I deactivated the plugin to remove all devices from homekit and reactivated again but still exposed as window. 
Any hint how to reset  to get the shelly plus2PM to be shown as Windowcover??

**Comment by dcdanielcoelho** [comment]
> Version 1.6.0 that I just released adds a configuration option for changing the cover type from Window to Window Covering or Door. 

>> The problem still persists, I tried everything, and the default always remains in window, in homebridge and homekit.
Any fixes in development? @alexryd
Tks.

**Comment by doviz** [comment]
> I have the same issue. With the shelly plus2pm set to cover-mode it was initially recognized als window, after setting "cover:0": { "exclude": false, "type": "windowCovering" it is still exposed as window. I deactivated the plugin to remove all devices from homekit and reactivated again but still exposed as window. Any hint how to reset to get the shelly plus2PM to be shown as Windowcover??

I also just encountered this issue.  After upgrading my phone to ios17 even though my shelly config has not changed from windowCovering home app thinks it is a window.  Perhaps, there is another way to define windowCovering starting in ios 17?

**Comment by nivohavi** [comment]
encountered the same issue, shelly config set to windowCovering but home app thinks it is a window...
@alexryd, any new ? :)

**Comment by SilvioMigu** [comment]
Hello
So it appears to be an iOS issue
On Android or others, does it work well?

Mine is IOS and I can't change it.

**Comment by fcremer** [comment]
Still the same. Tested on ios17 and ios18 Beta 1

**Comment by MaDDeePee** [comment]
Its no bug, its you.
JSON you need:
{
                    "id": "shellyplus2pm-XXXXXXXXXX",
                    "cover:0": {
                        "exclude": false,
                        "type": "windowCovering"
                    }
  }

working here, good luck!
