### ISSUE TITLE
ShellyPro1 unknown Device

### ISSUE THREAD

**Issue by Dolphinquarter** [alexryd/homebridge-shelly-ng#33]
Hi, 

I installed a Shelly Pro 1 with latest firmware and still get unknown device.
Does anyone know why? 
It ist a supported device!?

[7/10/2022, 9:01:23 PM] [Shelly NG] [shellypro1-30c6f7813af4] Unknown device of model "SPSW-201XE16EU" discovered.

{"name":null,"id":"shellypro1-30c6f7813af4","mac":"30C6F7813AF4","model":"SPSW-201XE16EU","gen":2,"fw_id":"20220617-111854/0.10.3-g7c89a05","ver":"0.10.3","app":"Pro1","auth_en":false,"auth_domain":null}

**Comment by alexryd** [comment]
Your devices are of a 2nd revision. Support for them will come in the next update.

**Comment by plaappi** [comment]
> Your devices are of a 2nd revision. Support for them will come in the next update.

Thanks, no wonder i could not get them to work :)

**Comment by alexryd** [comment]
I just released version 1.5.0 that supports your devices.

**Comment by plaappi** [comment]
> Shelly Pro1PM

Discovered right away with 0 Conf and On / Off switch works, thanks

**Comment by tweaksalot** [comment]
out of curiosity, any idea what changed in their hardware revision update that caused this?
