### ISSUE TITLE
Feature Request - Support Shelly Plug Plus

### ISSUE THREAD

**Issue by devsfan3** [alexryd/homebridge-shelly-ng#34]
Hello, is it possible to add support for the Shelly Plug Plus?

Thanks!

**Comment by alexryd** [comment]
As far as I can tell, no Plus Plug has been released yet?

**Comment by devsfan3** [comment]
Shelly Plus Plug US officially launched at today's product announcement.

**Comment by alexryd** [comment]
I just released version 1.5.0 that supports the new Shelly Plus Plug US.

**Comment by devsfan3** [comment]
Thanks - I just update and can confirm it's working for me!
