### ISSUE TITLE
Power Readings issue - need to be divided by 1000 to show in KWH

### ISSUE THREAD

**Issue by rionshin** [alexryd/homebridge-shelly-ng#35]
Update! 
I can see the readings in Eve, however there is an issue with total consumption - it come from Shelly in Wh not in KWH , however you send it as kWh and it shows I have 5000kwh consumption. 
you should divide by 1000 before send it to HomeKit. 
thank you so much for this amazing update ! 
![75935A83-1296-4438-9E3D-E538F8409DC1](https://user-images.githubusercontent.com/41396180/179267702-8840821e-6936-4d54-b045-4201c74fa2c8.png)

**Comment by rionshin** [comment]
You can see the same readings from HA
![Uploading FA04B1EA-F5EA-42FA-8D25-68CA7CDB6FEC.png…]()

**Comment by alexryd** [comment]
Ok! I just published version 1.4.1 that fixes this issue.

**Comment by rionshin** [comment]
> Ok! I just published version 1.4.1 that fixes this issue.

Thank you so much !
