### ISSUE TITLE
This plugin generated a warning from the characteristic

### ISSUE THREAD

**Issue by Kasper05** [alexryd/homebridge-shelly-ng#38]
Log file gives the following error.

[homebridge-shelly-ng] This plugin generated a warning from the characteristic 'Voltage': characteristic was supplied illegal value: number 257.8 exceeded maximum of 250. See https://homebridge.io/w/JtMGR for more info.

**Comment by eliziox** [comment]
Normally, Issue already fixed, upgrade the plugin

JSP

Le 20 juil. 2022 à 22:19, Kasper05 ***@***.***> a écrit :

﻿

Log file gives the following error.

[homebridge-shelly-ng] This plugin generated a warning from the characteristic 'Voltage': characteristic was supplied illegal value: number 257.8 exceeded maximum of 250. See https://homebridge.io/w/JtMGR for more info.

**Comment by Kasper05** [comment]
I have install the last version.
The error are not gone

**Comment by tojorocha** [comment]
i have the same problem…
waiting for a solution…

**Comment by alexryd** [comment]
The problem is that homebridge caches all characteristics. You need to remove your device from homebridge and then add it again to fix this warning.
