### ISSUE TITLE
Devices not showing up in Homebridge

### ISSUE THREAD

**Issue by jonathanlang** [alexryd/homebridge-shelly-ng#39]
I have two Shelly NG devices (Shelly Plus 1, Shelly Plus 2PM) on the network, and one of them is not showing up in the NG plugin. 
I can see in the homebridge log that both devices are discovered using mDNS, but only one of them is correctly identified: 
[25/07/2022, 18:27:37] [Shelly NG] [Gäste] Device added
[25/07/2022, 18:27:37] [Shelly NG] [shellyplus2pm-441793a7abc0] Unknown device of model "SNSW-102P16EU" discovered.

Seems the Shelly Plus 2PM is not known to the plugin yet? 

Thanks
Jonathan

**Comment by jonathanlang** [comment]
This is what the Shelly Plus 2PM self reports under IP/shelly: 

{"name":"Terrasse","id":"shellyplus2pm-441793a7abc0","mac":"441793A7ABC0","model":"SNSW-102P16EU","gen":2,"fw_id":"20220617-113003/0.10.3-g7c89a05","ver":"0.10.3","app":"Plus2PM","auth_en":false,"auth_domain":null,"profile":"switch"}

**Comment by alexryd** [comment]
You have a new version of the Plus 2 PM. Support for it will come in the next update.

**Comment by jonathanlang** [comment]
Hi Alex,
just installed 1.5.0 of Shelly NG. After rebooting Homebridge I still see this message: 
[09/08/2022, 14:54:03] [Shelly NG] [Gäste] Device added
[09/08/2022, 14:54:05] [Shelly NG] [shellyplus2pm-441793a7abc0] Unknown device of model "SNSW-102P16EU" discovered. 

And I can only see the one Shelly 1 PM I was able to see before listed in Home under the Shelly NG bridge. 

Is there something I can check? 
<img width="360" alt="image" src="https://user-images.githubusercontent.com/1255480/183652789-f5bad628-9fbb-4482-90ed-f4a345d020a5.png">

**Comment by alexryd** [comment]
I see. That model ID is missing from the documentation. Anyway I've added support for it in version 1.5.1.

**Comment by jonathanlang** [comment]
Amazing, can confirm it works perfectly now.

**Comment by alexryd** [comment]
Great!
