### ISSUE TITLE
Add a Shelly 1 plus manually 

### ISSUE THREAD

**Issue by ncapeyron** [alexryd/homebridge-shelly-ng#4]
Hello @alexryd ! 
How to add manually a Shelly 1 plus ? 
My devices are on a separate network and the automatic discovery doesn't work... So I want to add all manually.

Thanks for your answer :)

**Comment by alexryd** [comment]
This is coming in the next update.

**Comment by alexryd** [comment]
Using version 1.1.0 that I just released, devices can now be added manually by adding their IP addresses or host names to the config (using the `"hostname"` option), e.g:

```
{
  "platform": "ShellyNG",
  "name": "Shelly NG",
  "devices": [
    {
      "id": "shellyplus1-abcdef123456",
      "hostname": "192.168.1.25"
    },
    {
      "id": "shellyplus1pm-abcdef123457",
      "hostname": "192.168.1.50"
    }
  ]
}
```

**Comment by ncapeyron** [comment]
Super nice !!!
I wasn’t expecting a so quick answer !
I will test that as soon as possible. 
Thanks a lot
