### ISSUE TITLE
ShellyPlus1-63EFAC Unknown device of model "undefined" discovered.

### ISSUE THREAD

**Issue by jantox** [alexryd/homebridge-shelly-ng#46]
Hi, i just got a shelly plus 1 and i have the 0.11.0 Firmware installed, i get this error when in Homebridge, i also tried to add it via the plugin using id and ip of the device but i get the same issue. 

is it because of the firmware or is it a new revision of the device? it is weird that the model is "undefined" 

here is my /shelly data

{"name":"Licht","id":"ShellyPlus1-63EFAC","mac":"7C87CE63EFAC","gen":2,"fw_id":"20220830-130249/0.11.0-gfa1bc37","ver":"0.11.0","app":"Plus1","auth_en":true,"auth_domain":"ShellyPlus1-63EFAC"}

**Comment by ctschach** [comment]
Thats a known problem with Firmware 0.11.0. You also have issues installing the Shelly into Homeassistant. 

That's also the reason why Shelly has pulled the 0.11.0 firmware. You can downgrade to the previous version via the web-browser and everything will work as expected.

**Comment by jantox** [comment]
thank you for the answer. unfortunately i can't downgrade with the web browser, because it is a plus 1 and when i click on update, nothing happens. 
is there a link to the older firmware available somwhere so i can just flash the old firmware version?

**Comment by AirPett** [comment]
This problem still exists with Shelly FW 0.13.0 and the 0.14.0 beta. Would it be possible to have changes in this plugin to reflect the new device ID syntax? They now only have a part of the MAC and have uppercase characters i.e. ShellyPlus1-63EFAC from above. Could the plugin allow this?

**Comment by s-reimann** [comment]
I had the same problem, but it's working now after upgrading Homebridge to v1.6.0 and Shelly (Plus 1) firmware to 20230308-091529/0.14.1-g22a4cb7:
```
Loaded plugin: homebridge-shelly-ng@1.6.0
Registering platform 'homebridge-shelly-ng.ShellyNG'
[Shelly NG] Initializing ShellyNG platform...
[Shelly NG] [Shelly] Device added
```

**Comment by jantox** [comment]
yea they fixed it in an update :)
