### ISSUE TITLE
Shelly PRO 1

### ISSUE THREAD

**Issue by pieter-1978** [alexryd/homebridge-shelly-ng#5]
Hi Alex,

today I just installed a Shelly PRO 1, can you let me know if this device is already supported?

I now got below message in Homebridge:

[02/02/2022, 20:22:22] [Shelly NG] [shellypro1-_deviceID_] Unknown device of model "SPSW-001XE16EU" discovered.

I tried to add it manually but this doesn't  work. Looking at the supported devices I think this one is not (yet) supported?

If I need to test or gather info please let me know

Many thanks!

**Comment by alexryd** [comment]
I just released version 1.2.0 that adds support for the Shelly Pro 1 and a few other devices. Let me know if it’s working for you.

**Comment by pieter-1978** [comment]
@alexryd : just version 1.2.0 and it works like a charm!

many thanks for the quick support!
