### ISSUE TITLE
Shelly Plus I4

### ISSUE THREAD

**Issue by SpaceRichard** [alexryd/homebridge-shelly-ng#6]
Hi @alexryd ,

do you see the chance to include the Shelly Plus i4?
I will install 2 the next days, so if you need some feedback or testing, I could help if possible!

Thanks for working in the NG devices!

**Comment by alexryd** [comment]
Yes definitely.
If you can go to `http://<ip-address>/shelly` with the IP address of one of your I4s and then post the output here, that would help.

**Comment by SpaceRichard** [comment]
Done

`{"name":"Name", "id":"shellyplusi4-083af200dffc", "mac":"083AF200DFFC", "model":"SNSN-0024X", "gen":2, "fw_id":"20220120-094630/i4prod1-g480b553", "ver":"i4prod1", "app":"PlusI4", "auth_en":false,"auth_domain":null}`

**Comment by SpaceRichard** [comment]
Hi @alexryd 

just a short question, as I facing this "issue" currently with the Shelly i3 with your 1st Gen plugin.
Will it be possible to see the actions/state within HomeBridge, for the i3 there is no visual sign if the input is active.

Or is that in general not possible, for the i3/i4 ? 

The reason behind, I use in addition to homeBridge also node Red wich get the devices via HomeBridge.
But I can't see any action.

Thanks
Richard

**Comment by alexryd** [comment]
My other plugin doesn't support the i3 in switch mode, is that what you are referring to? That you can't see whether the switch is turned on or off? In that case, yes that will be supported for the i4.

**Comment by SpaceRichard** [comment]
No I not referred to the „Toogle switch“, just the Momentary mode. 
So that I get the short-press, long-press and double-press event passed to the system. 

Is that is supported I would be happy. 
(for the i3 I’m currently not sure where the look for a solution. But here is the wrong place) 

thanks.

**Comment by alexryd** [comment]
Version 1.3.0 now supports the I4.
