### ISSUE TITLE
Exlude only one Chanel from Shelly Pro 4 PM

### ISSUE THREAD

**Issue by Kai9555** [alexryd/homebridge-shelly-ng#8]
Is it possible to exlude only one chanel from a Shelly Pro 4 PM? Inside the Shelley App, the Chanels have a"_1" or _2" at the end of the ID like "shellypro4pm-abcdefg12345_2". 

However, when I enter that ID shellypro4pm-abcdefg12345_2, nothing happens. Without the "_2" suffix, the entire Shelly is excluded.

THX

**Comment by alexryd** [comment]
That's not possible yet but the plan is that it will be soon.

**Comment by Kai9555** [comment]
Sounds perfect :)

**Comment by alexryd** [comment]
Better late than never, with version 1.6.0 there are now options to exclude individual switches.

**Comment by Kai9555** [comment]
> 

perfect!!!!!
