### ISSUE TITLE
Roller shutter shown as Window in HK (Shelly 2PM)

### ISSUE THREAD

**Issue by t0mmey** [alexryd/homebridge-shelly-ng#94]
<img width="988" alt="Bildschirmfoto 2023-11-07 um 12 13 47" src="https://github.com/alexryd/homebridge-shelly-ng/assets/130061934/f58a6816-267e-4661-b6d0-1c9e323f3b97">
<img width="329" alt="Bildschirmfoto 2023-11-07 um 12 40 28" src="https://github.com/alexryd/homebridge-shelly-ng/assets/130061934/1d888a34-5789-4e10-a693-484e82779e93">

Hi all, just set up a Shelly 2PM, changed to cover and calibrated it.
The plugin is discovering the device but shows in Homebridge as a weird icon and in HomeKit it is shown as window. Any idea what I am doing wrong? I didn’t add a manual config to homebridge.

**Comment by janbl** [comment]
I have just changed the cover type to windowCovering and it shows up as a cover
`                    "cover:0": {`
`                       "exclude": false,`
`                       "type": "windowCovering"`
`                    }`

**Comment by t0mmey** [comment]
> I have just changed the cover type to windowCovering and it shows up as a cover ` "cover:0": {` ` "exclude": false,` ` "type": "windowCovering"` ` }`

Thanks @janbl. I am a bit confused how to add this code the Config in terms of Syntax. I am using Hoobs, do I just need to put it in like this?
<img width="320" alt="Bildschirmfoto 2023-11-09 um 14 54 16" src="https://github.com/alexryd/homebridge-shelly-ng/assets/130061934/3aca4f27-40a4-4fe7-83d4-e2bd46baf826">

**Comment by t0mmey** [comment]
@janbl got the Syntax and its working now! Thanks again

**Comment by b123luke** [comment]
HI @t0mmey i have the same problem and also using hoobs, can you send your complete config file for this Plugin? thanks

**Comment by t0mmey** [comment]
Hi @b123luke, my config file contains logins and PWs :/ would it be ok if I just share the Shelly NG part?

In Hoobs, go to Settings and then o Advanced. Here you see the plain config file.

Under "Platforms" insert a new platform as per below:

{
            "name": "Shelly NG",
            "mdns": {
                "enable": true
            },
            "devices": [
                {
                    "id": "ShellyPlus2PM-The12DigitIDofYourShelly",
                    "name": "Rolladen WZ Mitte",
                    "exclude": false,
                    "switch:0": {
                        "exclude": false,
                        "type": "switch"
                    },
                    "switch:1": {
                        "exclude": false,
                        "type": "switch"
                    },
                    "switch:2": {
                        "exclude": false,
                        "type": "switch"
                    },
                    "switch:3": {
                        "exclude": false,
                        "type": "switch"
                    },
                    "cover:0": {
                        "exclude": false,
                        "type": "windowCovering"
                    }
                }
            ],
            "platform": "ShellyNG"
        }

Once you hit save, the bridge should restart. then check the log file to see if a line appears similar to the one below (note that the name needs to be replaced by the name that you have entered in the code above under 'name'for your blind):
HOOBSShelly NG[Rolladen WZ Mitte] Device added

Let me know if that works for you.

As an aside: I have been trying the code yesterday and it was not working for whatever reason. I might had a syntax issue or the ID was wrong.

**Comment by b123luke** [comment]
HI @t0mmey, thanks for your help but it does not work....
My config:
{
    "platform": "Shelly NG",
    "name": "Shelly NG",
    "devices": [
        {
            "id": "shellyplus2pm-90380c3859d0",
            "name": "Store Sitzplatz N",
            "exclude": false,
	"hostname": "192.168.XXX.XXX",
            "switch:0": {
                "exclude": false,
                "type": "switch"
            },
            "switch:1": {
                "exclude": false,
                "type": "switch"
            },
            "switch:2": {
                "exclude": false,
                "type": "switch"
            },
            "switch:3": {
                "exclude": false,
                "type": "switch"
            },
            "cover:0": {
                "exclude": false,
                "type": "windowCovering"
            }
        }
    ]
}

Also at the log file i see nothing, just the Shelly IDs

**Comment by t0mmey** [comment]
@b123luke 
Hmm, for testing, did you try adding my code and just add the ID of your Shelly? If that works, may be start customizing according to your needs.

Also, I remember the plugin adds a another „platform“ entry in the log file with no additional attributes. I have removed that one and had just my code there.

**Comment by b123luke** [comment]
Hi @t0mmey
Thanks for your support, now its working, but im not very sure why....

**Comment by SilvioMigu** [comment]
hey guys
I have the same problem
I've already tried your settings and I can't change the Homekit app to windowcovering.
Are yours working?
You can share your settings again, so I can paste them in my hoobs settings.
Thanks

**Comment by t0mmey** [comment]
Hi @SilvioMigu 
For testing, did you try adding my code and just add the ID of your Shelly? If that works, may be start customizing according to your needs.

Also, I remember the plugin adds a another „platform“ entry in the log file with no additional attributes. I have removed that one and had just my code there.

Once you have added the code and your Hoobs is rebooting, check the log file to see if your shelly gets added

**Comment by SilvioMigu** [comment]
Hello @t0mmey 
Yes, I've already tested your code and others here on the forum and it never changes from cover to windownCovering.
In the hoobs log, shelly 2pm is always added.

I already deleted it from the cache, and then installed the plugin again.
I turned off Shelly's electricity so it wouldn't be added, before I put the code with the id information and the windowCovering information.
Even so, when I turn on the power, the shelly is added and does not appear again as a cover in the homekit app.
I don't understand
I'm doing something wrong, I don't know what.

**Comment by SilvioMigu** [comment]
Can you show me how your code is?
It's in the advanced section, where you have the code, right?

**Comment by SilvioMigu** [comment]
What is Syntax, which you mention?

**Comment by SilvioMigu** [comment]
![Captura de ecrã 2023-12-07, às 15 20 59](https://github.com/alexryd/homebridge-shelly-ng/assets/67691682/69cd4c5a-8433-4c52-9624-3b50d91ecb75)


This is my last configuration, for shelly 2pm
I've tried the others too

**Comment by t0mmey** [comment]
@SilvioMigu maybe that's the difference: I didn't use the config field of the plugin.

Instead I went to settings of Hoobs, opened the plain config file and insterted the code there.

<img width="320" alt="Bildschirmfoto 2023-12-07 um 16 42 10" src="https://github.com/alexryd/homebridge-shelly-ng/assets/130061934/2eda95e0-6b44-4b63-a344-f5c82eb88189">

**Comment by SilvioMigu** [comment]
Where do I do this on Hoobs?

Do I click on advanced?

**Comment by t0mmey** [comment]
Yes, the gear wheel in the left lower corner and then advanced. See if you have already an area in the code called "platforms" where other platforms have been added already and just add the code mentioned previously.

**Comment by SilvioMigu** [comment]
![Captura de ecrã 2023-12-07, às 16 23 21](https://github.com/alexryd/homebridge-shelly-ng/assets/67691682/ce8a0b4b-824a-4293-8440-fde3e3b9857a)
Already appears here

Erase it and put it back in again?

**Comment by SilvioMigu** [comment]
I only have written "platforms" at the beginning of the code

Now I deleted the plugin and reinstalled it

appears at the end, like this:
![Captura de ecrã 2023-12-07, às 17 06 28](https://github.com/alexryd/homebridge-shelly-ng/assets/67691682/188e68d0-dcb7-46b5-ab3f-2f5584ab999b)

**Comment by SilvioMigu** [comment]
Your firmware, is that?

![image](https://github.com/alexryd/homebridge-shelly-ng/assets/67691682/2d7f53a0-2bb4-4603-a9f0-b77e16971882)

**Comment by SilvioMigu** [comment]
I already got it
thanks for the support
see here: https://github.com/alexryd/homebridge-shelly-ng/issues/56
